import { getHexagramInfo } from "./hexagrams";
import { getTemporalTexture, describeNeighbourhood, getNeighbourhood } from "./kingwen";
import { downloadMarkdown } from "./exportSession";
import { participantsToLines, participantsToChangingLine } from "./groupCast";
import type { Circle } from "@/types/circle";

export { downloadMarkdown };

function renderLine(yang: boolean): string {
  return yang ? "━━━━━━━━━" : "━━━━ ━━━━";
}

function renderHexagram(lines: boolean[], changingLine?: number | null): string {
  const rows: string[] = [];
  for (let i = 5; i >= 0; i--) {
    const marker = changingLine != null && changingLine - 1 === i ? "  ◄" : "";
    rows.push(`${renderLine(lines[i])}  ${i + 1}${marker}`);
  }
  return rows.join("\n");
}

function relativeTime(ms: number): string {
  const now = Date.now();
  const diff = Math.floor((now - ms) / 1000);
  if (diff < 60) return "just now";
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
  return `${Math.floor(diff / 86400)}d ago`;
}

export function exportCircle(circle: Circle): string {
  const exportDate = new Date().toISOString().slice(0, 10);
  const createdDate = new Date(circle.createdAt);

  // Neighbourhood at creation time
  const texture = getTemporalTexture(createdDate);
  const neighbourhood = getNeighbourhood(createdDate, 14);
  const prose = describeNeighbourhood(neighbourhood);

  // Group hexagram
  const lines = participantsToLines(circle.participants);
  const changingLine = participantsToChangingLine(circle.participants);
  const presentInfo = getHexagramInfo(lines);

  let futureSection = "";
  if (changingLine !== null && circle.participants.length > 0) {
    const futureLines = [...lines];
    futureLines[changingLine - 1] = !futureLines[changingLine - 1];
    const futureInfo = getHexagramInfo(futureLines);
    futureSection = `
## Future Influence — Hexagram ${futureInfo.number}: ${futureInfo.name}
[Reference](${futureInfo.url})

\`\`\`
${renderHexagram(futureLines)}
\`\`\`
`;
  }

  // Distilled inquiry
  const inquirySection = circle.inquiry
    ? `> **${circle.inquiry}**`
    : "_No inquiry question set._";

  // Fragments
  const fragmentsSection = circle.fragments.length === 0
    ? "_No fragments recorded._"
    : circle.fragments
        .map((f) => {
          const who = f.author ? `**${f.author}**` : "_anonymous_";
          return `> ${f.text}\n>\n> — ${who}, ${relativeTime(f.addedAt)}`;
        })
        .join("\n\n");

  // Individual casts
  const individualSection = circle.participants.length === 0
    ? "_No participants submitted a cast._"
    : circle.participants
        .map((p) => {
          const pLines = p.numbers.slice(0, 6).map((n) => n % 2 === 1);
          const pInfo = getHexagramInfo(pLines);
          const who = p.name ?? p.deviceId.slice(0, 8);
          return [
            `### ${who} — Hexagram ${pInfo.number}: ${pInfo.name}`,
            `[Reference](${pInfo.url})`,
            "",
            "```",
            renderHexagram(pLines),
            "```",
          ].join("\n");
        })
        .join("\n\n");

  const presentSection = circle.participants.length > 0
    ? `## The Circle's Hexagram — Hexagram ${presentInfo.number}: ${presentInfo.name}
[Reference](${presentInfo.url})

\`\`\`
${renderHexagram(lines, changingLine)}
\`\`\`
${changingLine !== null ? `\n**Changing Line:** ${changingLine}` : ""}
${futureSection}`
    : "_No participants yet — hexagram will appear once someone casts._";

  return `# Collective Circle — ${circle.id}

**Exported:** ${exportDate}
**Circle created:** ${createdDate.toISOString().slice(0, 10)}
**Participants at export:** ${circle.participants.length}
**Fragments:** ${circle.fragments.length}

---

## Neighbourhood of Now (at creation)

Cycle position ${texture.cyclePosition} of 384 · FOD weight ${texture.fodValue}

${prose}

---

## The Inquiry

${inquirySection}

## The Collection

${fragmentsSection}

---

${presentSection}

---

## Individual Casts

${individualSection}

---

*Generated by weching — Collective Circle*
`;
}
