import { getHexagramInfo } from "./hexagrams";
import { analyzeThread, describeTransition } from "./operators";
import { downloadMarkdown } from "./exportSession";
import type { TemporalReading } from "@/types/thread";

export { downloadMarkdown };

function renderLine(yang: boolean): string {
  return yang ? "━━━━━━━━━" : "━━━━ ━━━━";
}

function renderHexagram(lines: boolean[], changingLine?: number | null): string {
  const rows: string[] = [];
  for (let i = 5; i >= 0; i--) {
    const marker =
      changingLine != null && changingLine - 1 === i ? "  ◄" : "";
    rows.push(`${renderLine(lines[i])}  ${i + 1}${marker}`);
  }
  return rows.join("\n");
}

export function exportThread(readings: TemporalReading[]): string {
  if (readings.length === 0) return "# Thread of Selves\n\nNo readings recorded.";

  const analysis = analyzeThread(readings);
  const exportDate = new Date().toISOString().slice(0, 10);

  const readingsSections = readings
    .map((r, i) => {
      const info = getHexagramInfo(r.lines);
      const parts = [
        `### Reading ${i + 1} — ${r.date}`,
        r.label ? `**Context:** ${r.label}` : "",
        r.inquiry ? `**Inquiry:** "${r.inquiry}"` : "",
        `**Hexagram ${info.number}: ${info.name}**`,
        `[Reference](${info.url})`,
        "",
        "```",
        renderHexagram(r.lines, r.changingLine),
        "```",
      ].filter((l) => l !== "");

      if (r.changingLine) {
        const derivedLines = [...r.lines];
        derivedLines[r.changingLine - 1] = !derivedLines[r.changingLine - 1];
        const derivedInfo = getHexagramInfo(derivedLines);
        parts.push(
          "",
          `**Changing line ${r.changingLine} points toward — Hexagram ${derivedInfo.number}: ${derivedInfo.name}**`,
          `[Reference](${derivedInfo.url})`,
          "",
          "```",
          renderHexagram(derivedLines),
          "```",
        );
      }

      return parts.join("\n");
    })
    .join("\n\n");

  const transitionsSections = analysis.transitions
    .map((t) => {
      const from = readings[t.fromIndex];
      const to = readings[t.toIndex];
      const fromInfo = getHexagramInfo(from.lines);
      const toInfo = getHexagramInfo(to.lines);
      return [
        `**Reading ${t.fromIndex + 1} → Reading ${t.toIndex + 1}**`,
        `Operator: ${t.operator.map((b) => (b ? "1" : "0")).join("")}`,
        `Weight: ${t.hammingWeight} (${t.operatorClass}, ${t.trigramCharacter} trigram)`,
        ...describeTransition(t, readings).split("\n"),
      ].join("  \n");
    })
    .join("\n\n");

  const stableNote =
    analysis.stableLines.length > 0
      ? `Lines ${analysis.stableLines.join(", ")} held stable throughout all transitions.`
      : "No lines remained stable across all transitions.";

  const volatileNote =
    analysis.volatileLines.length > 0
      ? `Lines ${analysis.volatileLines.join(", ")} were most volatile (changed in ≥50% of transitions).`
      : "No lines changed with consistent frequency.";

  const firstInfo = getHexagramInfo(readings[0].lines);
  const presentInfo = analysis.presentHexagram;
  const trigramLabel = analysis.netTrigramCharacter === "both" ? "both trigrams" : `${analysis.netTrigramCharacter} trigram`;

  return `# Thread of Selves

**Exported:** ${exportDate}
**Readings:** ${readings.length}

---

## Readings

${readingsSections}

---

## Transitions

${transitionsSections}

---

## Net Transformation

**From:** Hexagram ${firstInfo.number} (${firstInfo.name})
**To:** Hexagram ${presentInfo.number} (${presentInfo.name})

**Net operator:** ${analysis.netOperator.map((b) => (b ? "1" : "0")).join("")}
**Net weight:** ${analysis.netHammingWeight} (${trigramLabel})

${stableNote}
${volatileNote}

---

*Generated by Thread of Selves — weching*
`;
}
