"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FormingTheQuestion = FormingTheQuestion;
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
const StepLayout_1 = require("@/components/StepLayout");
function FormingTheQuestion({ onContinue, onBack, onSkip, }) {
    return ((0, jsx_runtime_1.jsxs)(StepLayout_1.StepLayout, { onContinue: onContinue, onBack: onBack, onSkip: onSkip, children: [(0, jsx_runtime_1.jsxs)("h2", { className: "text-2xl font-serif tracking-wide text-primary flex items-center justify-center", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.MessageCircle, { className: "w-6 h-6 mr-3" }), "Forming the Question"] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-6", children: [(0, jsx_runtime_1.jsx)("p", { className: "text-foreground/80 font-serif", children: "Approaching the I Ching requires that you ask a question. What do you, deep down, really want more clarity on? What is truly on your heart?" }), (0, jsx_runtime_1.jsx)("p", { className: "text-foreground/80 font-serif", children: "This inquiry is the heart of the ritual. Everything that follows \u2014 the seeds, the counting, the hexagram \u2014 serves as a response to the question you bring. Give this step the time it deserves." }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-4", children: [(0, jsx_runtime_1.jsxs)("h3", { className: "text-lg font-serif font-medium text-primary flex items-center", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.MessageCircle, { className: "w-4 h-4 mr-2" }), "Group Process"] }), (0, jsx_runtime_1.jsx)("p", { className: "text-foreground/80 font-serif", children: "Each participant should first handwrite their individual inquiry in their journal. Then share and discuss to form a collective question." }), (0, jsx_runtime_1.jsx)("p", { className: "text-foreground/80 font-serif", children: "The process is intentionally messy and non-linear \u2014 conversation and synthesis are key." })] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-4", children: [(0, jsx_runtime_1.jsxs)("h3", { className: "text-lg font-serif font-medium text-primary flex items-center", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Pencil, { className: "w-4 h-4 mr-2" }), "Crafting Your Inquiry"] }), (0, jsx_runtime_1.jsx)("p", { className: "text-foreground/80 font-serif", children: "Your inquiry can be a question, statement, observation, or image. Poetry reflecting on your situation is also effective." }), (0, jsx_runtime_1.jsx)("p", { className: "text-foreground/80 font-serif", children: "The more specific and heartfelt, the more profound and precisely tailored the response will be." })] }), (0, jsx_runtime_1.jsx)("div", { className: "bg-meditation-glow p-4 rounded-lg", children: (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-muted-foreground font-serif italic", children: "The hardest part is arriving at the shared inquiry \u2014 this is where the real work begins. Take your time with this crucial step before proceeding to the seed ritual." }) })] })] }));
}
