"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Preparation = Preparation;
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
const StepLayout_1 = require("@/components/StepLayout");
function Preparation({ onContinue, onBack, onSkip }) {
    return ((0, jsx_runtime_1.jsxs)(StepLayout_1.StepLayout, { onContinue: onContinue, onBack: onBack, onSkip: onSkip, children: [(0, jsx_runtime_1.jsxs)("h2", { className: "text-2xl font-serif tracking-wide text-primary flex items-center justify-center", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Flower2, { className: "w-6 h-6 mr-3" }), "Preparation"] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-6", children: [(0, jsx_runtime_1.jsxs)("div", { className: "space-y-4", children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-lg font-serif font-medium text-primary", children: "Creating Space" }), (0, jsx_runtime_1.jsx)("p", { className: "text-foreground/80 font-serif", children: "Create a centered and centering space, uncluttered and unfettered from outside distractions. Shut off devices and notifications." }), (0, jsx_runtime_1.jsx)("p", { className: "text-foreground/80 font-serif", children: "Set up an altar \u2014 a flat space with cloth to prevent seeds from rolling or mixing. Decorate with meaningful objects: crystals, stones, driftwood, or natural pieces." })] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-4", children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-lg font-serif font-medium text-primary", children: "Seed Selection" }), (0, jsx_runtime_1.jsx)("p", { className: "text-foreground/80 font-serif", children: "Prepare a small dish with seeds approximately the size of rice grains. Rice works well, or any seeds that are easy to manipulate and count without difficulty." }), (0, jsx_runtime_1.jsx)("p", { className: "text-foreground/80 font-serif", children: "Seeds that are too small make counting challenging. Focus on odd/even totals rather than exact counts." })] })] })] }));
}
