"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.downloadMarkdown = void 0;
exports.exportThread = exportThread;
const hexagrams_1 = require("./hexagrams");
const operators_1 = require("./operators");
const exportSession_1 = require("./exportSession");
Object.defineProperty(exports, "downloadMarkdown", { enumerable: true, get: function () { return exportSession_1.downloadMarkdown; } });
function renderLine(yang) {
    return yang ? "━━━━━━━━━" : "━━━━ ━━━━";
}
function renderHexagram(lines, changingLine) {
    const rows = [];
    for (let i = 5; i >= 0; i--) {
        const marker = changingLine != null && changingLine - 1 === i ? "  ◄" : "";
        rows.push(`${renderLine(lines[i])}  ${i + 1}${marker}`);
    }
    return rows.join("\n");
}
function exportThread(readings) {
    if (readings.length === 0)
        return "# Thread of Selves\n\nNo readings recorded.";
    const analysis = (0, operators_1.analyzeThread)(readings);
    const exportDate = new Date().toISOString().slice(0, 10);
    const readingsSections = readings
        .map((r, i) => {
        const info = (0, hexagrams_1.getHexagramInfo)(r.lines);
        const lines = [
            `### Reading ${i + 1} — ${r.date}`,
            r.label ? `**Context:** ${r.label}` : "",
            r.inquiry ? `**Inquiry:** "${r.inquiry}"` : "",
            `**Hexagram ${info.number}: ${info.name}**`,
            `[Reference](${info.url})`,
            "",
            "```",
            renderHexagram(r.lines, r.changingLine),
            "```",
        ]
            .filter((l) => l !== "")
            .join("\n");
        return lines;
    })
        .join("\n\n");
    const transitionsSections = analysis.transitions
        .map((t) => {
        const from = readings[t.fromIndex];
        const to = readings[t.toIndex];
        const fromInfo = (0, hexagrams_1.getHexagramInfo)(from.lines);
        const toInfo = (0, hexagrams_1.getHexagramInfo)(to.lines);
        return [
            `**Reading ${t.fromIndex + 1} → Reading ${t.toIndex + 1}**`,
            `Hexagram ${fromInfo.number} → ${toInfo.number}`,
            `Operator: ${t.operator.map((b) => (b ? "1" : "0")).join("")}`,
            `Weight: ${t.hammingWeight} (${t.operatorClass}, ${t.trigramCharacter} trigram)`,
            (0, operators_1.describeTransition)(t, readings),
        ].join("  \n");
    })
        .join("\n\n");
    const stableNote = analysis.stableLines.length > 0
        ? `Lines ${analysis.stableLines.join(", ")} held stable throughout all transitions.`
        : "No lines remained stable across all transitions.";
    const volatileNote = analysis.volatileLines.length > 0
        ? `Lines ${analysis.volatileLines.join(", ")} were most volatile (changed in ≥50% of transitions).`
        : "No lines changed with consistent frequency.";
    const netInfo = (0, hexagrams_1.getHexagramInfo)(readings[readings.length - 1].lines.map((v, i) => (analysis.netOperator[i] ? !v : v)));
    void netInfo; // net is from first to last; present is just last
    const presentInfo = analysis.presentHexagram;
    return `# Thread of Selves

**Exported:** ${exportDate}
**Readings:** ${readings.length}

---

## Readings

${readingsSections}

---

## Transitions

${transitionsSections}

---

## Net Transformation

**From:** Hexagram ${(0, hexagrams_1.getHexagramInfo)(readings[0].lines).number} (${(0, hexagrams_1.getHexagramInfo)(readings[0].lines).name})
**To:** Hexagram ${presentInfo.number} (${presentInfo.name})

**Net operator:** ${analysis.netOperator.map((b) => (b ? "1" : "0")).join("")}
**Net weight:** ${analysis.netHammingWeight} (${analysis.netTrigramCharacter} trigram)

${stableNote}
${volatileNote}

${analysis.resultingHexagram
        ? `**Resulting hexagram** (from changing line): Hexagram ${analysis.resultingHexagram.number} — ${analysis.resultingHexagram.name}`
        : ""}

---

*Generated by Thread of Selves — weching*
`;
}
