services:
  app:
    image: ${APP_IMAGE}
    restart: always
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=weching.honour.community
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=weching.honour.community
      - DB_PATH=/data/weching.db
    env_file: .env
    volumes:
      - ./data:/data
    networks:
      - serve

networks:
  serve:
    external: true
