"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StepLayout = StepLayout;
const jsx_runtime_1 = require("react/jsx-runtime");
const button_1 = require("@/components/ui/button");
const lucide_react_1 = require("lucide-react");
function StepLayout({ children, onBack, onContinue, onSkip, continueLabel = "Continue", backLabel = "Back", showBack = true, showContinue = true, showSkip = true, }) {
    return ((0, jsx_runtime_1.jsx)("div", { className: "min-h-screen flex flex-col pt-4", children: (0, jsx_runtime_1.jsx)("div", { className: "flex-1 flex items-center justify-center px-4 py-12", children: (0, jsx_runtime_1.jsxs)("div", { className: "max-w-2xl mx-auto w-full", children: [(0, jsx_runtime_1.jsx)("div", { className: "text-base leading-relaxed space-y-6", children: children }), (0, jsx_runtime_1.jsxs)("div", { className: "mt-12 flex flex-col sm:flex-row items-center justify-between gap-4", children: [(0, jsx_runtime_1.jsx)("div", { className: "order-3 sm:order-1 sm:w-1/3", children: showBack && onBack && ((0, jsx_runtime_1.jsxs)(button_1.Button, { variant: "ghost", onClick: onBack, className: "font-serif text-muted-foreground hover:text-foreground", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.ArrowLeft, { className: "w-4 h-4 mr-2" }), backLabel] })) }), (0, jsx_runtime_1.jsx)("div", { className: "order-1 sm:order-2 sm:w-1/3 flex justify-center", children: showContinue && onContinue && ((0, jsx_runtime_1.jsxs)(button_1.Button, { onClick: onContinue, size: "lg", className: "px-8 font-serif shadow-warm hover:shadow-meditation transition-all duration-300", children: [continueLabel, (0, jsx_runtime_1.jsx)(lucide_react_1.ArrowRight, { className: "w-4 h-4 ml-2" })] })) }), (0, jsx_runtime_1.jsx)("div", { className: "order-2 sm:order-3 sm:w-1/3 flex justify-center sm:justify-end", children: showSkip && onSkip && ((0, jsx_runtime_1.jsx)("button", { onClick: onSkip, className: "font-serif text-sm text-muted-foreground hover:text-foreground transition-colors duration-200 underline underline-offset-4 decoration-muted-foreground/30 whitespace-nowrap", children: "Skip to Ceremony \u2192" })) })] })] }) }) }));
}
